packages:
  - .

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

overrides:
  '@intlify/shared': '11.4.10'
  '@intlify/core': '11.4.10'
  '@intlify/core-base': '11.4.10'
  '@intlify/message-compiler': '11.4.10'
  '@intlify/devtools-types': '11.4.10'
